# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'webmock/rspec'
require 'codeclimate-test-reporter'
require 'simplecov'
CodeClimate::TestReporter.start
SimpleCov.start

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.after(:suite) do
    WebMock.disable_net_connect!(allow: 'codeclimate.com')
  end
end

def source_root
  File.expand_path('../../', __FILE__)
end

AUTH_XML = File.read('spec/responses/authenticate_response.xml')
SECRET_XML = File.read('spec/responses/get_secret_response.xml')
SECRET_WITH_KEY_XML = File.read('spec/responses/get_secret_with_keys_response.xml')
SECRET_WITH_ATTACHMENT_XML = File.read('spec/responses/get_secret_with_attachment_response.xml')
PRIVATE_KEY_XML = File.read('spec/responses/download_private_key_response.xml')
PUBLIC_KEY_XML = File.read('spec/responses/download_public_key_response.xml')
ATTACHMENT_XML = File.read('spec/responses/attachment_response.xml')
